prax-wallet/registry

- .github/workflows/npm-publish.yml
Applying proper working directory and permissions
> Changeset action bug fix

- npm/CHANGELOG.md
- npm/package.json
- npm/src/client.ts
- npm/src/index.ts
Some were private and consumers need to import them.
> Expose all ts interfaces

- README.md
- input/penumbra-testnet-deimos-6.json
- npm/CHANGELOG.md
- npm/package.json
- npm/src/client.ts
- registry/penumbra-testnet-deimos-6.json
- tools/compiler/src/parser.rs
- tools/compiler/src/processor.rs
- tools/compiler/src/querier.rs
- tools/compiler/tests/test_processor.rs
Adding displayName & images to chain registry (needed in frontend). Also did some renaming work to add clarity.
> Augment ibc connections with name+images

- input/penumbra-testnet-deimos-6.json
- registry/penumbra-testnet-deimos-6.json
```
+------------+----------+--------------+-------------------------+----------------+-----------------+---------------+
| Channel ID | Port     | Counterparty | Counterparty Channel ID | State          | Client ID       | Client Height |
+===================================================================================================================+
| channel-0  | transfer | osmo-test-5  | channel-6679            | CLIENT EXPIRED | 07-tendermint-2 | 5-6272218     |
|------------+----------+--------------+-------------------------+----------------+-----------------+---------------|
| channel-1  | transfer | grand-1      | channel-149             | OPEN           | 07-tendermint-3 | 1-6167400     |
|------------+----------+--------------+-------------------------+----------------+----- …
```
> Update to latest testnet channel ids

- input/penumbra-testnet-deimos-6.json
- registry/penumbra-testnet-deimos-6.json
Deleting the v6 registry files broke devnet instances running v6 of testnet. This PR restores those files.
> Add back v6 registry files

- input/penumbra-testnet-deimos-7.json
- registry/penumbra-testnet-deimos-7.json
New channel for osmosis available. Allows for IBC'ing in.
> Update osmosis channel

- npm/CHANGELOG.md
- npm/package.json
> Add changeset for deimos-8

- README.md
- input/penumbra-testnet-deimos-8.json
- npm/CHANGELOG.md
- npm/package.json
- registry/penumbra-testnet-deimos-8.json
> Update to latest noble channels

- README.md
- tools/compiler/Cargo.lock
- tools/compiler/Cargo.toml
> Add detailed instructions for adding to registry

- input/penumbra-testnet-deimos-8.json
- npm/CHANGELOG.md
- npm/package.json
- registry/penumbra-testnet-deimos-8.json
Closes https://github.com/prax-wallet/registry/issues/37
> Update noble ibc channel

- npm/CHANGELOG.md
- npm/package.json
Follow up from: https://github.com/prax-wallet/registry/pull/38
> Deploy starling addition

- input/penumbra-testnet-deimos-8.json
- npm/CHANGELOG.md
- npm/package.json
- registry/penumbra-testnet-deimos-8.json
Addresses are out of date + updating to proper symbol structure
> Fix penumbra labs validator infos

- input/penumbra-testnet-deimos-8.json
- npm/CHANGELOG.md
- npm/package.json
- registry/penumbra-testnet-deimos-8.json
wtest_eth, test_sat, utest_atom, utest_osmo
> Add more testnet tokens

- input/penumbra-testnet-deimos-6.json
- input/penumbra-testnet-deimos-7.json
- input/penumbra-testnet-deimos-8.json
- npm/CHANGELOG.md
- npm/package.json
- npm/pnpm-lock.yaml
- npm/src/json.ts
- npm/src/registry.test.ts
- npm/src/registry.ts
- registry/penumbra-testnet-deimos-6.json
- registry/penumbra-testnet-deimos-7.json
- registry/penumbra-testnet-deimos-8.json
- tools/compiler/Cargo.lock
- tools/compiler/Cargo.toml
- tools/compiler/src/parser.rs
- tools/compiler/src/processor.rs
- tools/compiler/tests/test_parser.rs
Related to: https://github.com/penumbra-zone/web/issues/1230
We want to move frontends to the registry so minifront can reference this list instead of hardcoding.
> List frontends in registry

- npm/CHANGELOG.md
- npm/package.json
- npm/src/client.test.ts
- npm/src/json.ts
- registry/globals.json
- tools/compiler/src/processor.rs
- tools/compiler/tests/test_copy_globals.rs
Allows consumers of the raw json be able to use bufbuild tools to deserialize
> Store stakingAssetId as proto-compatible type

- input/globals.json
Not added to input it will get deleted on a cargo run
> Add registry to input

- input/chains/penumbra-1.json
- registry/chains/penumbra-1.json
> Initial penumbra-1 ibc connections

- npm/.changeset/clever-keys-impress.md
- npm/.changeset/metal-toys-unite.md
- npm/CHANGELOG.md
- npm/package.json
Update the registry to v11.0.0
> chore: bump versions

- npm/CHANGELOG.md
- npm/package.json
- npm/pnpm-lock.yaml
- npm/src/utils/testnet-parser.test.ts
> Prep v11.3 npm release

- input/chains/penumbra-1.json
- input/chains/penumbra-testnet-deimos-8-x6de97e39.json
- npm/src/registry.test.ts
- registry/chains/penumbra-1.json
- registry/chains/penumbra-testnet-deimos-8-x6de97e39.json
Reverts prax-wallet/registry#106
Users reporting errors on shield page given bufbuild will not deserialize the extra field until those protobufs are updated first. Reverting until those updates are propagated.
> Revert "Add badges to registry"

- input/chains/penumbra-testnet-phobos-2.json
- registry/chains/penumbra-testnet-phobos-2.json
Helpful for Dex Explorer default trading pairs page
> Add testnet priority scores

- input/chains/penumbra-1.json
- npm/CHANGELOG.md
- npm/package.json
- registry/chains/penumbra-1.json
- registry/chains/penumbra-testnet-deimos-8-x6de97e39.json
- registry/chains/penumbra-testnet-phobos-1.json
- registry/chains/penumbra-testnet-phobos-2-x4120f355.json
- registry/chains/penumbra-testnet-phobos-2.json
- tools/compiler/Cargo.lock
- tools/compiler/Cargo.toml
- tools/compiler/src/parser.rs
- tools/compiler/src/processor.rs
> Add coingecko ids to assets

- npm/CHANGELOG.md
- npm/package.json
hopefully this fixes clobbered `v12.3.0` release
> registry: bump deps

- input/chains/penumbra-testnet-phobos-3.json
- registry/chains/penumbra-testnet-phobos-3.json
Generated a new config for the fresh testnet chain. To create this, I copied the old phobos-2 config as a base, then manually edited the values for the IBC channels and the validator delegation token names.
> add new chain penumbra-testnet-phobos-3
