registry/penumbra-testnet-deimos-6.json, tools/compiler/src/processor.rs
Instead of having the assets in a flat list, I think it will be more useful for consumers if they have a map, since the point is to be able to look up assets by ID. I used the Base64 encoding of the `AssetId` proto's `inner` field, on the theory that this is the most accessible thing for code that doesn't have access to Penumbra structure but wants to interpret an `AssetId` anyways.
=> Change registry to store assets by (base64) ID

npm/CHANGELOG.md, npm/package.json, npm/pnpm-lock.yaml, npm/src/client.ts, npm/src/github.ts, npm/src/index.ts, npm/src/registry.test.ts, npm/src/registry.ts, npm/src/utils.test.ts, npm/src/utils.ts
Allows consumers not to need to worry about how to deserialize the json values of the protobufs. Also provides a helper method to retrieve metadata by assetId.
=> Create registry class helper

input/penumbra-testnet-deimos-6.json, input/penumbra-testnet-deimos-7.json, npm/CHANGELOG.md, npm/package.json, npm/src/registry.test.ts, npm/src/registry.ts, registry/penumbra-testnet-deimos-6.json, registry/penumbra-testnet-deimos-7.json, tools/compiler/src/parser.rs, tools/compiler/src/processor.rs, tools/compiler/tests/test_processor.rs
Consumers need to know what is the counterparty channel id for our IBC connections. Instead of having to query+map for this data, we'll just add them to the registry.
=> Add counter party channels to registry

input/penumbra-testnet-deimos-8.json, npm/CHANGELOG.md, npm/package.json, registry/penumbra-testnet-deimos-8.json
Updates the Osmosis <-> Penumbra channel for `penumbra-testnet-deimos-8` (https://github.com/penumbra-zone/penumbra/issues/4374), post-resolution of recent Hermes instability (https://github.com/penumbra-zone/penumbra/issues/4310). 
Please take a hard look at the diff, because this is my first time mucking around in this repo. What I did:
0. Inspect new channel via `pcli q ibc channels`. It's `channel-3` on Penumbra and `channel-7867` on the Osmosis side.
1. Edit `input/penumbra-testnet-deimos-8.json` to update those values. 
2. `cd tools/compiler && cargo run`
3. Commit, push, PR.
If I overlooked anything, please teach me to fish!
=> chore: update osmosis channel for deimos-8

input/chains/penumbra-testnet-deimos-6.json, input/chains/penumbra-testnet-deimos-7.json, input/chains/penumbra-testnet-deimos-8.json, input/globals.json, npm/CHANGELOG.md, npm/package.json, npm/src/client.ts, npm/src/json.ts, npm/src/registry.test.ts, npm/src/registry.ts, registry/chains/penumbra-testnet-deimos-6.json, registry/chains/penumbra-testnet-deimos-7.json, registry/chains/penumbra-testnet-deimos-8.json, registry/globals.json, tools/compiler/Cargo.lock, tools/compiler/Cargo.toml, tools/compiler/src/parser.rs, tools/compiler/src/processor.rs, tools/compiler/tests/test_copy_globals.rs, tools/compiler/tests/test_get_chain_configs.rs, tools/compiler/tests/test_reset_registry_dir.rs
Previously, you needed a chain id to get rpcs+frontends. This PR makes those available without the need for a chain id.
Also adds various helpers+tests.
=> Make rpcs+frontends global values

npm/CHANGELOG.md, npm/package.json, npm/pnpm-lock.yaml, npm/src/json.ts, npm/src/registry.test.ts, npm/src/registry.ts, registry/chains/penumbra-testnet-deimos-6.json, registry/chains/penumbra-testnet-deimos-7.json, registry/chains/penumbra-testnet-deimos-8.json, registry/globals.json, tools/compiler/Cargo.lock, tools/compiler/Cargo.toml, tools/compiler/src/parser.rs, tools/compiler/src/processor.rs, tools/compiler/tests/test_copy_globals.rs
At the moment, these are chain-id by chain-id based. Given this will be the same no matter what chain id, moving this to globals. This also allows Prax to be able to reference it even when the RPC's chain id is not in the registry.
Unblocks onboarding work: https://github.com/prax-wallet/web/pull/66
=> Add stakingAssetId to globals

input/chains/penumbra-testnet-deimos-8.json, registry/chains/penumbra-testnet-deimos-8.json
The osmo-grand-5 client expired roughly a week ago, due to the osmosis testnet rpc node experiencing turbulence. After Testnet 78 [0], and confirming that the osmosis node was working again, we created a new channel.
[0] https://github.com/penumbra-zone/penumbra/issues/4582
=> chore: update osmo test channel for testnet 78

npm/CHANGELOG.md, npm/package.json, npm/pnpm-lock.yaml, npm/src/client.test.ts, npm/src/utils/testnet-parser.test.ts, npm/src/utils/testnet-parser.ts
Preview chainId's no longer have a hex at the end, but a number
=> Update testnet preview matcher

npm/.changeset/metal-toys-unite.md, npm/src/utils/testnet-parser.test.ts, npm/src/utils/testnet-parser.ts
Closes #62 
Tested on multiple local devnets. Found the pattern that they all have a hexadecimal ending string of length 8. Preview nets prefix this string with an '-x'. That's why I simply extended the `isTestnetPreviewChainId` function by updating the regexp
=> feat: #62: add support for local devnets

input/globals.json, npm/.changeset/chatty-onions-happen.md, npm/.changeset/clever-keys-impress.md, npm/src/github.ts, npm/src/globals.test.ts, npm/src/globals.ts, npm/src/json.ts, npm/src/registry.ts, npm/src/remote.test.ts, registry/globals.json, tools/compiler/Cargo.lock, tools/compiler/Cargo.toml, tools/compiler/src/parser.rs, tools/compiler/src/processor.rs, tools/compiler/tests/test_copy_globals.rs, tools/compiler/tests/test_get_chain_configs.rs
Closes #60 
Add the `websites` field to `globals`. The same as `frontends` but with `name` and `images` fields, following RPC structure
=> feat: #60: add `websites` to globals

registry/chains/penumbra-1.json
We encountered some frustrating deserialization errors that we traced to a duplicated upstream commit [0].
[0] https://github.com/cosmos/chain-registry/pull/5089
=> chore: regenerate from upstream chain-registry

input/chains/penumbra-testnet-deimos-8-x6de97e39.json, registry/chains/penumbra-testnet-deimos-8-x6de97e39.json
Adding reference to the latest iteration of the Penumbra testnet, with chain id penumbra-testnet-deimos-8-x6de97e39.
=> chore: add latest penumbra testnet

input/chains/penumbra-testnet-deimos-8.json, npm/src/bundled.test.ts, npm/src/registry.test.ts, registry/chains/penumbra-testnet-deimos-8.json
During IBC dev spike, we discovered that the prax registry logic is hardcoded to pull from a `penumbra-testnet-deimos-8.json`, even if that's not the testnet chain id that a user is connected to.
We should update that logic, but to unblock, I'm clobbering the old config with the new config, manually, to force loading of the correct IBC channels.
=> fix: clobber old penumbra testnet config

input/chains/penumbra-testnet-phobos-1.json, registry/chains/penumbra-testnet-phobos-1.json
Unlike with #71 & #72, where we intentionally clobbered the old `deimos-8` chain
config, I'm placing this as its own new config, because the lack of
suffix should prevent the mishandling of the lookup via the registry
URL.
=> chore: new penumbra devnet

npm/CHANGELOG.md, npm/package.json, npm/pnpm-lock.yaml, npm/src/bundled.test.ts, npm/src/client.ts, npm/src/globals.ts, npm/src/json.ts, npm/src/registry.test.ts, npm/src/registry.ts, npm/src/remote.test.ts, npm/src/remote.ts
Been a while since we cut a version of the npm package. Helpful for https://github.com/prax-wallet/web/issues/166.
- Latest registry gets bundled
- Closes https://github.com/prax-wallet/registry/issues/83
- Adds new `getWithBundledBackup` method to remote client
=> Bundle latest into v11.1

.github/workflows/rust-checks.yml, input/chains/penumbra-testnet-phobos-2-x4120f355.json, registry/chains/penumbra-testnet-phobos-2-x4120f355.json
Working on creating a long-running testnet, and the chain `penumbra-testnet-phobos-2-x4120f355` is undergoing team review. As part of that review, I'm updating the prax asset registry, so that prax workflows display correct information regarding the ibc testnet assets.
=> chore: add draft testnet phobos-2-x4120f355

input/chains/penumbra-testnet-phobos-2.json, registry/chains/penumbra-testnet-phobos-2.json
After team review of draft chain `penumbra-testnet-phobos-2-x4120f355`, we're finalizing the testnet config as `penumbra-testnet-phobos-2`. Updating the prax asset registry to match, particularly the validator IDs and the IBC channel info.
=> chore: add testnet phobos-2

npm/CHANGELOG.md, npm/package.json, npm/src/json.ts
Follow-up to #92, in which we overlooked a small change required to ship the new asset registry in #91. Refs https://github.com/penumbra-zone/dex-explorer/issues/57.
=> fix: export phobos-2 registry

input/chains/penumbra-1.json, registry/chains/penumbra-1.json
Does two things:
1. Adds `transfer/channel-2/uusdc` as a numeraire for the `penumbra-1` chain. This will allow consumers (like Prax) to start indexing prices in that denom.
2. Updates cosmos chain registry submodule to latest (some additional assets are added)
=> Add penumbra-1 numeraire

input/chains/penumbra-testnet-phobos-2.json, registry/chains/penumbra-testnet-phobos-2.json
The noble <-> penumbra channel expired on `penumbra-testnet-phobos-2`. Still diagnosing root cause, but we manually created a new channel, to unblock development, so I'm updating the asset registry immediately.
=> fix: new noble channel for phobos-2 testnet

.github/workflows/npm-publish.yml
Diagnosing failing run: https://github.com/prax-wallet/registry/actions/runs/11475999397
This permission prevents the action from running with the correct permissions
=> Remove permission limit from github action

npm/.changeset/small-islands-bathe.md, npm/CHANGELOG.md, npm/package.json, npm/pnpm-lock.yaml, npm/src/registry.test.ts, npm/src/registry.ts
Closes https://github.com/prax-wallet/registry/issues/99
=> Add fallible tryGetMetadata method

npm/CHANGELOG.md, npm/package.json, npm/src/globals.ts, npm/src/registry.ts
Relates to https://github.com/prax-wallet/registry/pull/107
Given the new badges field, when deserializing Json, it's important to have the `ignoreUnknownFields` field set. If not, forward compatible Metadata changes will throw an error. This future proofs this type.
We will have to update frontends to this new registry version (and wait some time) before re-adding badges in main.
=> Ignore unknown fields

input/chains/penumbra-testnet-phobos-2.json, npm/.changeset/warm-shoes-tell.md, npm/pnpm-lock.yaml, registry/chains/penumbra-testnet-phobos-2.json
This PR:
- updates the active channels to noble, duke, and osmosis testnets for `phobos-2`
=> registry: update `phobos-2` channels

input/chains/penumbra-1.json, input/chains/penumbra-testnet-deimos-8-x6de97e39.json, input/chains/penumbra-testnet-phobos-1.json, input/chains/penumbra-testnet-phobos-2-x4120f355.json, input/chains/penumbra-testnet-phobos-2.json, npm/.changeset/spotty-carpets-bathe.md, registry/chains/penumbra-1.json, registry/chains/penumbra-testnet-deimos-8-x6de97e39.json, registry/chains/penumbra-testnet-phobos-1.json, registry/chains/penumbra-testnet-phobos-2-x4120f355.json, registry/chains/penumbra-testnet-phobos-2.json
It felt wrong that the native token didn't have name and description in its own registry. Also, it feels logical to tokens filter by name, so searching for "penumbra" in different products couldn't find the UM token
Let me know if there could be a better text in the description field
=> feat: add name and description to Penumbra token

npm/CHANGELOG.md, npm/package.json, npm/pnpm-lock.yaml
Consuming coingecko ids wasn't working, because the Registry npm package was using an old version of the protobuf pkg, that didn't have the coingeckoId field, and was therefore deserializing the Metadata incorrectly. This PR fixes this.
=> fix: upgrade protobuf pkg to fix coingecko ids

input/chains/penumbra-testnet-phobos-2.json, npm/.changeset/brave-cows-hunt.md, npm/CHANGELOG.md, npm/package.json, registry/chains/penumbra-testnet-phobos-2.json, tools/compiler/src/processor.rs
Fairly straightforward change: bump the osmo testnet channel. 
I'd like to _verify_ that this setting works, in a local build of prax, but have been unable to do so. Documented some suggestions in https://github.com/prax-wallet/registry/issues/80#issuecomment-2635529847.
=> chore: update testnet channels again

npm/.changeset/healthy-chairs-mate.md, npm/src/registry.test.ts, npm/src/registry.ts
Querying metadata by denom should use `base` field instead of `display`
=> fix: get metadata by denom using base field

npm/.changeset/shaggy-dogs-attend.md, npm/CHANGELOG.md, npm/package.json, npm/src/json.ts
Fixes the NPM registry for the Phobos3 chain and upgrades JS package version
=> feat(npm): add phobos 3 to bundled npm registry

input/chains/penumbra-1.json, npm/CHANGELOG.md, npm/package.json, registry/chains/penumbra-1.json
This PR:
- overrides the alloyed ETH ticker to `allETH`
- records injective and dydx channel metadata
=> registry: rename allETH and add dydx/inj channels

input/chains/penumbra-testnet-phobos-3.json, npm/CHANGELOG.md, npm/package.json, registry/chains/penumbra-testnet-phobos-3.json
The phobos-3 channels expired during planned endpoint downtime last week, due to extremely short unbonding period of 240 blocks on the phobos-3 chain. That unbonding period has since been raised to 60480 blocks, roughly 1 week, so that new clients will use the longer value.
This PR updates the registry with newly created channels, per standard procedure.
Initially, I tried to preserve the old, expired assets for legibility's sake during LQT testing (https://github.com/penumbra-zone/penumbra/issues/5010). However, the shape of the implementation to achieve that legibility isn't clear to me, so I'm punting on that for now; we can follow up in a second PR.
=> chore: update phobos-3 testnet channels

input/globals.json, npm/CHANGELOG.md, npm/package.json, registry/globals.json
The Simply Staking RPC endpoint is down, returning a 502. Radiant Commons helpfully wrangled the other community RPCs to updating to a new enough version of `pd` to support the new Frontier RPC [0], which is used by a forthcoming version of Prax [1]. Since Staking is down, they can't update, so let's remove them from the bundled list of RPC options. Once they're back up we can consider re-adding.
[0] https://github.com/penumbra-zone/penumbra/pull/5179
[1] https://github.com/prax-wallet/prax/pull/336
=> remove Simply Staking from RPC list

.github/workflows/npm-publish.yml
Since release of v1.5.2 of the github action helper for changesets [0], relative paths are no longer working when specifying the cwd for the action. See more info in [1].
[0] https://github.com/changesets/action/releases/tag/v1.5.2
[1] https://github.com/changesets/action/issues/475
=> ci: fix changeset cwd to absolute path

npm/CHANGELOG.md, npm/package.json, npm/src/client.ts, npm/src/github.ts, npm/src/options.ts, npm/src/remote.ts
By default, NextJS provides a polyfill of the fetch API: https://nextjs.org/docs/app/api-reference/functions/fetch
We use fetch to get the remote Github resources.
In the browser, our current code will use the browser cache well, caching the result based on the headers Github gives us, which, by default, cache it for 5 minutes.
On the server though, when using NextJS, caching will **never happen**. By default, their polyfilled fetch will not cache anything, and you instead need to pass `'force-cache'`.
Their semantics for this are the same as `'default'` in the browser.
We also can't just pass this option blindly, because in the browser, this will have the wrong effect, and always use the cache, even if stale.
So, we need to figure out if we're in NextJS, and modify the behavior …
=> feat: allow consumers to enable caching for NextJS
